name: i_billing
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  cached_network_image: ^3.4.0
#  intl: ^0.17.0
  shimmer: ^3.0.0
  lottie: ^3.1.2
  flutter_screenutil: ^5.9.3
  device_preview: ^1.2.0
  google_fonts: ^6.2.1
  flutter_svg: ^2.0.14
  cupertino_icons: ^1.0.8
  l: ^4.0.2
  dropdown_button2: ^2.3.9
  table_calendar: ^3.1.3

#  localization
  easy_localization: ^3.0.7

  #  state management
  bloc: ^8.1.4
  flutter_bloc: ^8.1.6
  get_it: ^8.0.2
  json_serializable: ^6.8.0
  json_annotation: ^4.9.0
  freezed: ^2.5.2
  freezed_annotation: ^2.4.4

#  storage
  flutter_secure_storage: ^9.2.2

#  netwokd
  dio: ^5.7.0
  connectivity_plus: ^6.1.1



dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/
    - assets/translations/
    - assets/fonts/



  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins/Poppins-Black.ttf
          weight: 900
        - asset: assets/fonts/Poppins/Poppins-BlackItalic.ttf
          weight: 900
          style: italic

        - asset: assets/fonts/Poppins/Poppins-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Poppins/Poppins-ExtraBoldItalic.ttf
          weight: 800
          style: italic

        - asset: assets/fonts/Poppins/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins/Poppins-BoldItalic.ttf
          weight: 700
          style: italic

        - asset: assets/fonts/Poppins/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins/Poppins-SemiBoldItalic.ttf
          weight: 600
          style: italic

        - asset: assets/fonts/Poppins/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins/Poppins-MediumItalic.ttf
          weight: 500
          style: italic

        - asset: assets/fonts/Poppins/Poppins-Regular.ttf
          weight: 400

        - asset: assets/fonts/Poppins/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins/Poppins-LightItalic.ttf
          weight: 300
          style: italic

        - asset: assets/fonts/Poppins/Poppins-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Poppins/Poppins-ExtraLightItalic.ttf
          weight: 200
          style: italic

        - asset: assets/fonts/Poppins/Poppins-Thin.ttf
          weight: 100
        - asset: assets/fonts/Poppins/Poppins-ThinItalic.ttf
          weight: 100
          style: italic

        - asset: assets/fonts/Poppins/Poppins-Italic.ttf
    - family: Ubuntu
      fonts:
        - asset: assets/fonts/Ubuntu/Ubuntu-Bold.ttf
          weight: 700
          style: normal
        - asset: assets/fonts/Ubuntu/Ubuntu-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/Ubuntu/Ubuntu-Medium.ttf
          weight: 500
          style: normal
        - asset: assets/fonts/Ubuntu/Ubuntu-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Ubuntu/Ubuntu-Regular.ttf
          weight: 400
          style: normal
        - asset: assets/fonts/Ubuntu/Ubuntu-Light.ttf
          weight: 300
          style: normal
        - asset: assets/fonts/Ubuntu/Ubuntu-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/Ubuntu/Ubuntu-Italic.ttf
          style: italic
